fix for greenplum-db#8558

diff --git a/GNUmakefile.in b/GNUmakefile.in
--- a/GNUmakefile.in
+++ b/GNUmakefile.in
@@ -123,23 +123,21 @@ check check-tests installcheck installcheck-parallel installcheck-tests: CHECKPR
 check check-tests installcheck installcheck-parallel installcheck-tests: submake-generated-headers
 	$(MAKE) -C src/test/regress $@
 
-cluster_check_and_run:
-	rc=`PGPORT=5432 && pg_isready 1>/dev/null && echo $$? || echo $$?`; \
-	echo RV = $$rc ; \
-	if test $$rc = "0" ; then \
-	    echo "Found cluster on standard port" ; \
-	    exit 1; \
-	fi
-	@echo "Start checking Demo cluster"
-	@$(MAKE) -C $(top_builddir) check-demo-cluster 1>/dev/null
-	@echo "run demo-cluster"
-	@. $(prefix)/greenplum_path.sh && $(MAKE) -C $(top_builddir) create-demo-cluster
-
 check:
-	@echo "check and run GP-cluster..."
-	-$(MAKE) -C $(top_builddir) cluster_check_and_run && { echo "Cluster was started"; } || { echo "Cluster was found"; }
-	@echo "run tests..."
-	-@ . $(prefix)/greenplum_path.sh && .  $(top_builddir)/gpAux/gpdemo/gpdemo-env.sh && $(MAKE) -C  $(top_builddir) installcheck
+	rc=`PGPORT=5432 && pg_isready 1>/dev/null && echo $$? || echo $$?`; \
+	if test $$rc != "0" ; then \
+	  echo "Not found cluster on standard port, starting demo" ; \
+	  rc=`$(MAKE) -C $(top_builddir) check-demo-cluster 1>/dev/null && echo $$? || echo $$?`; \
+	  if test $$rc = "0" ; then \
+	     echo "Demo cluster not found, starting new..." ; \
+	     . $(prefix)/greenplum_path.sh && $(MAKE) -C $(top_builddir) create-demo-cluster; \
+	  fi ; \
+	  echo "Start installcheck against demo cluster"; \
+	  . $(prefix)/greenplum_path.sh && .  $(top_builddir)/gpAux/gpdemo/gpdemo-env.sh && $(MAKE) -C  $(top_builddir) installcheck ; \
+	else \
+	  echo "Start installcheck against existing cluster" ;\
+	  -@ $(MAKE) -C  $(top_builddir) installcheck ;\
+	fi
 
 $(call recurse,check-world,src/test src/pl src/interfaces/ecpg contrib src/bin gpcontrib,check)
 $(call recurse,checkprep,  src/test src/pl src/interfaces/ecpg contrib src/bin gpcontrib)
